### ISSUE TITLE
nodebb-plugin-sso-soundcloud breaks NodeBB login overall

### ISSUE THREAD

**Issue by RobertBroersma** [jaredhanson/passport-soundcloud#3]
It depends on passport-soundcloud and it breaks also the local strategy. I suspect it is because of the dependencies of passport-soundcloud, but I'm not sure. Therefore if you can help me it would be awesome, otherwise feel free to close/remove.

Basically same problem as in this issue I think, but then with SC: https://github.com/jaredhanson/passport/issues/400

**Comment by Eiryyy** [comment]
@RobertBroersma I guess it will resolve if `passport-oauth` of dependency is updated to 1.0.0.
